package com.zd.manager.account.model;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_parent_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private Integer permissionParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_type
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_sign
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String permissionSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_url
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_level
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private Integer permissionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_description
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String permissionDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_id
     *
     * @return the value of permission.permission_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_id
     *
     * @param permissionId the value for permission.permission_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_parent_id
     *
     * @return the value of permission.permission_parent_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public Integer getPermissionParentId() {
        return permissionParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_parent_id
     *
     * @param permissionParentId the value for permission.permission_parent_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionParentId(Integer permissionParentId) {
        this.permissionParentId = permissionParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_type
     *
     * @return the value of permission.permission_type
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_type
     *
     * @param permissionType the value for permission.permission_type
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_sign
     *
     * @return the value of permission.permission_sign
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getPermissionSign() {
        return permissionSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_sign
     *
     * @param permissionSign the value for permission.permission_sign
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionSign(String permissionSign) {
        this.permissionSign = permissionSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_url
     *
     * @return the value of permission.permission_url
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_url
     *
     * @param permissionUrl the value for permission.permission_url
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_level
     *
     * @return the value of permission.permission_level
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public Integer getPermissionLevel() {
        return permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_level
     *
     * @param permissionLevel the value for permission.permission_level
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionLevel(Integer permissionLevel) {
        this.permissionLevel = permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_description
     *
     * @return the value of permission.permission_description
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_description
     *
     * @param permissionDescription the value for permission.permission_description
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription;
    }
}