package com.zd.manager.account.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_sign
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String roleSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_level
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private Integer roleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_description
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    private String roleDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_sign
     *
     * @return the value of role.role_sign
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getRoleSign() {
        return roleSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_sign
     *
     * @param roleSign the value for role.role_sign
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setRoleSign(String roleSign) {
        this.roleSign = roleSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_level
     *
     * @return the value of role.role_level
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public Integer getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_level
     *
     * @param roleLevel the value for role.role_level
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setRoleLevel(Integer roleLevel) {
        this.roleLevel = roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_description
     *
     * @return the value of role.role_description
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_description
     *
     * @param roleDescription the value for role.role_description
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
}