package com.zd.manager.account.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.company
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.real_name
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param userName  the value for user.user_name
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.company
	 * @return  the value of user.company
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.company
	 * @param company  the value for user.company
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.real_name
	 * @return  the value of user.real_name
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.real_name
	 * @param realName  the value for user.real_name
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbg.generated  Tue Jul 10 10:41:25 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}