package com.zd.manager.business.mapper;

import java.util.List;

import com.zd.manager.business.model.Project;

public interface ProjectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int deleteByPrimaryKey(Integer projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int insert(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int insertSelective(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	Project selectByPrimaryKey(Integer projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int updateByPrimaryKeySelective(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int updateByPrimaryKey(Project record);

	/**
     * 查询所有项目
     * @return
     */
    List<Project> queryAll();

	List<Integer> queryProjectIdByName(List<String> projectNamesList);
}