package com.zd.manager.business.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zd.manager.business.model.Project;

public interface ProjectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int deleteByPrimaryKey(Integer projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int insert(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int insertSelective(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	Project selectByPrimaryKey(Integer projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int updateByPrimaryKeySelective(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Wed Aug 01 15:19:23 CST 2018
	 */
	int updateByPrimaryKey(Project record);

	/**
     * 查询所有项目
     * @return
     */
    List<Project> queryAll();

	List<Integer> queryProjectIdByName(List<String> projectNamesList);

	List<Project> queryProjectWithSomething(@Param("start")Integer start,@Param("end") Integer end,@Param("sortFeild") String sortFeild,@Param("order") String order);

	List<Project> queryProject(@Param("start")Integer start,@Param("end")Integer end,@Param("sortField") String sortField,@Param("sortOrder") String sortOrder,@Param("projectType") String[] projectType,
			@Param("projectStatus") String[] projectStatus,@Param("projectId")String projectId, @Param("projectName")String projectName, @Param("projectType1")String projectType2, @Param("projectAddress")String projectAddress, @Param("projectStatus1")String projectStatus2);

	Integer queryTotal(@Param("start")Integer start, @Param("end")Integer end, @Param("sortField")String sortField, @Param("sortOrder")String sortOrder,@Param("projectType") String[] projectType,
			@Param("projectStatus") String[] projectStatus, @Param("projectId")String projectId, @Param("projectName")String projectName, @Param("projectType1")String projectType2, @Param("projectAddress")String projectAddress, @Param("projectStatus1")String projectStatus2);
}