package com.zd.manager.business.mapper;

import com.zd.manager.business.model.Sensor;

public interface SensorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer sensorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(Sensor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(Sensor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    Sensor selectByPrimaryKey(Integer sensorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(Sensor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(Sensor record);
}