package com.zd.manager.business.mapper;

import com.zd.manager.business.model.SensorData;

public interface SensorDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor_data
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor_data
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(SensorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor_data
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(SensorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor_data
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    SensorData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor_data
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(SensorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor_data
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(SensorData record);
}