package com.zd.manager.business.mapper;

import com.zd.manager.business.model.StatisticChart;

public interface StatisticChartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_chart
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer statisticChartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_chart
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(StatisticChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_chart
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(StatisticChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_chart
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    StatisticChart selectByPrimaryKey(Integer statisticChartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_chart
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(StatisticChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_chart
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(StatisticChart record);
}