package com.zd.manager.business.mapper;

import com.zd.manager.business.model.SysCode;

public interface SysCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    SysCode selectByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(SysCode record);
}