package com.zd.manager.business.mapper;

import com.zd.manager.business.model.TerminalsLog;

public interface TerminalsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_log
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_log
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(TerminalsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_log
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(TerminalsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_log
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    TerminalsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_log
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(TerminalsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_log
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(TerminalsLog record);
}