package com.zd.manager.business.mapper;

import com.zd.manager.business.model.TerminalsProject;

public interface TerminalsProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer tpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(TerminalsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(TerminalsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    TerminalsProject selectByPrimaryKey(Integer tpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(TerminalsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(TerminalsProject record);
}