package com.zd.manager.business.mapper;

import com.zd.manager.business.model.Terminals;

public interface TerminalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(Terminals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(Terminals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    Terminals selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(Terminals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(Terminals record);
}