package com.zd.manager.business.mapper;

import java.util.List;

import com.zd.manager.business.model.Project;
import com.zd.manager.business.model.UserProject;

public interface UserProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    UserProject selectByPrimaryKey(Integer upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(UserProject record);
    
    /**
     * 根据用户id查询项目
     * @param userId
     * @return
     */
    List<Project> queryProjectByUserId(Integer userId);
    
    /**
     * 查询所有项目
     * @return
     */
    List<UserProject> queryAll();
}