package com.zd.manager.business.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zd.manager.account.model.User;
import com.zd.manager.business.model.Project;
import com.zd.manager.business.model.UserProject;

public interface UserProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int deleteByPrimaryKey(Integer upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insert(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int insertSelective(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    UserProject selectByPrimaryKey(Integer upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKeySelective(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    int updateByPrimaryKey(UserProject record);
    
    /**
     * 根据用户id查询项目
     * @param userId
     * @return
     */
    List<Project> queryProjectByUserId(Integer userId);
    
    /**
     * 查询所有项目
     * @return
     */
    List<UserProject> queryAll();
    
    /**
     * 根据用户id查询用户已有的项目id
     * @param userId
     * @return
     */
    List<Project> queryNoProjectByUserId(Integer userId);
    
    /**
     * 给指定用户名的用户添加项目
     * @param userName
     * @param projectNamesList
     * @return
     */
	int addProjectsToUser(String userName, List<String> projectNamesList);
	
	/**
	 * 根据用户名和项目名删除关联表数据
	 * @param userName
	 * @param projectName
	 * @return
	 */
	int deleteProject(@Param("userId")Integer userId, @Param("projectId")Integer projectId);
	
	/**
	 * 根据用户id删除关联数据
	 * @param userId
	 * @return
	 */
	int deleteByUserId(Integer userId);
	
	/**
	 * 根据项目id删除关联数据
	 * @param projectId
	 * @return
	 */
	int deleteByProjectId(Integer projectId);
	
	/**
	 * 根据项目id查询项目下用户
	 * @param projectId
	 */
	List<User> queryUserByProjectId(Integer projectId);
	
	/**
	 * 根据项目id查询项目未拥有用户
	 * @param projectId
	 * @return
	 */
	List<User> queryNoUserByProjectId(Integer projectId);
}