server:
  port: 8090
  
spring:
  datasource:
    # url: jdbc:mysql://123.207.88.210:3306/monitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: znyjy
    # password: zdjc@znyjy
    url: jdbc:mysql://localhost:3306/manager3?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  devtools:
    livereload:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml  
  type-aliases-package: com.zdjc.entity


com:
  manager:
    # 项目状态对应字典系统编码
    projectStatusTypeCode: 1
    # 区间角色对应字典系统编码
    sectorRoleTypeCode: 2