package com.zd.manager.account.mapper;

import com.zd.manager.account.model.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    int deleteByPrimaryKey(Integer rpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    RolePermission selectByPrimaryKey(Integer rpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Jul 10 10:41:25 CST 2018
     */
    int updateByPrimaryKey(RolePermission record);
}