package com.zd.manager.business.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Project implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_address
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String projectAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.weather_address
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String weatherAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_longitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String projectLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_latitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String projectLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_begin_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date projectBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_end_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date projectEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_description
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String projectDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_id
     *
     * @return the value of project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_id
     *
     * @param projectId the value for project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_type
     *
     * @return the value of project.project_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_type
     *
     * @param projectType the value for project.project_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectType(Integer projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_address
     *
     * @return the value of project.project_address
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getProjectAddress() {
        return projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_address
     *
     * @param projectAddress the value for project.project_address
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectAddress(String projectAddress) {
        this.projectAddress = projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.weather_address
     *
     * @return the value of project.weather_address
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getWeatherAddress() {
        return weatherAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.weather_address
     *
     * @param weatherAddress the value for project.weather_address
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setWeatherAddress(String weatherAddress) {
        this.weatherAddress = weatherAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_longitude
     *
     * @return the value of project.project_longitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getProjectLongitude() {
        return projectLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_longitude
     *
     * @param projectLongitude the value for project.project_longitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectLongitude(String projectLongitude) {
        this.projectLongitude = projectLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_latitude
     *
     * @return the value of project.project_latitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getProjectLatitude() {
        return projectLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_latitude
     *
     * @param projectLatitude the value for project.project_latitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectLatitude(String projectLatitude) {
        this.projectLatitude = projectLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_begin_time
     *
     * @return the value of project.project_begin_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getProjectBeginTime() {
        return projectBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_begin_time
     *
     * @param projectBeginTime the value for project.project_begin_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectBeginTime(Date projectBeginTime) {
        this.projectBeginTime = projectBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_end_time
     *
     * @return the value of project.project_end_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Date getProjectEndTime() {
        return projectEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_end_time
     *
     * @param projectEndTime the value for project.project_end_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectEndTime(Date projectEndTime) {
        this.projectEndTime = projectEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_status
     *
     * @return the value of project.project_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_status
     *
     * @param projectStatus the value for project.project_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectStatus(Integer projectStatus) {
        this.projectStatus = projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_description
     *
     * @return the value of project.project_description
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_description
     *
     * @param projectDescription the value for project.project_description
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription;
    }
}