package com.zd.manager.business.model;

import java.util.Date;

public class SensorData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.create_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.create_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String createType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.smu_cms_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuCmsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.smu_cms_channel
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuCmsChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.sensor_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer sensorStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.sensor_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Double sensorValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor_data.sensor_temperature
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Double sensorTemperature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.id
     *
     * @return the value of sensor_data.id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.id
     *
     * @param id the value for sensor_data.id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.create_time
     *
     * @return the value of sensor_data.create_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.create_time
     *
     * @param createTime the value for sensor_data.create_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.create_type
     *
     * @return the value of sensor_data.create_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getCreateType() {
        return createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.create_type
     *
     * @param createType the value for sensor_data.create_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setCreateType(String createType) {
        this.createType = createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.smu_cms_id
     *
     * @return the value of sensor_data.smu_cms_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuCmsId() {
        return smuCmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.smu_cms_id
     *
     * @param smuCmsId the value for sensor_data.smu_cms_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuCmsId(String smuCmsId) {
        this.smuCmsId = smuCmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.smu_cms_channel
     *
     * @return the value of sensor_data.smu_cms_channel
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuCmsChannel() {
        return smuCmsChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.smu_cms_channel
     *
     * @param smuCmsChannel the value for sensor_data.smu_cms_channel
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuCmsChannel(String smuCmsChannel) {
        this.smuCmsChannel = smuCmsChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.sensor_id
     *
     * @return the value of sensor_data.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.sensor_id
     *
     * @param sensorId the value for sensor_data.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorId(String sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.sensor_status
     *
     * @return the value of sensor_data.sensor_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getSensorStatus() {
        return sensorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.sensor_status
     *
     * @param sensorStatus the value for sensor_data.sensor_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorStatus(Integer sensorStatus) {
        this.sensorStatus = sensorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.sensor_value
     *
     * @return the value of sensor_data.sensor_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Double getSensorValue() {
        return sensorValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.sensor_value
     *
     * @param sensorValue the value for sensor_data.sensor_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorValue(Double sensorValue) {
        this.sensorValue = sensorValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor_data.sensor_temperature
     *
     * @return the value of sensor_data.sensor_temperature
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Double getSensorTemperature() {
        return sensorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor_data.sensor_temperature
     *
     * @param sensorTemperature the value for sensor_data.sensor_temperature
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorTemperature(Double sensorTemperature) {
        this.sensorTemperature = sensorTemperature;
    }
}