package com.zd.manager.business.model;

public class Sensor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer sensorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.monitor_point
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String monitorPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.monitor_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer monitorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.smu_number
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.smu_channel
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_number
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_model
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_longitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_latitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_place
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.sensor_depth
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Float sensorDepth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_id
     *
     * @return the value of sensor.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_id
     *
     * @param sensorId the value for sensor.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorId(Integer sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.project_id
     *
     * @return the value of sensor.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.project_id
     *
     * @param projectId the value for sensor.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.monitor_point
     *
     * @return the value of sensor.monitor_point
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getMonitorPoint() {
        return monitorPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.monitor_point
     *
     * @param monitorPoint the value for sensor.monitor_point
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setMonitorPoint(String monitorPoint) {
        this.monitorPoint = monitorPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.monitor_type
     *
     * @return the value of sensor.monitor_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getMonitorType() {
        return monitorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.monitor_type
     *
     * @param monitorType the value for sensor.monitor_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setMonitorType(Integer monitorType) {
        this.monitorType = monitorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.smu_number
     *
     * @return the value of sensor.smu_number
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuNumber() {
        return smuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.smu_number
     *
     * @param smuNumber the value for sensor.smu_number
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuNumber(String smuNumber) {
        this.smuNumber = smuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.smu_channel
     *
     * @return the value of sensor.smu_channel
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuChannel() {
        return smuChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.smu_channel
     *
     * @param smuChannel the value for sensor.smu_channel
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuChannel(String smuChannel) {
        this.smuChannel = smuChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_number
     *
     * @return the value of sensor.sensor_number
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorNumber() {
        return sensorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_number
     *
     * @param sensorNumber the value for sensor.sensor_number
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorNumber(String sensorNumber) {
        this.sensorNumber = sensorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_type
     *
     * @return the value of sensor.sensor_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorType() {
        return sensorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_type
     *
     * @param sensorType the value for sensor.sensor_type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorType(String sensorType) {
        this.sensorType = sensorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_model
     *
     * @return the value of sensor.sensor_model
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorModel() {
        return sensorModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_model
     *
     * @param sensorModel the value for sensor.sensor_model
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorModel(String sensorModel) {
        this.sensorModel = sensorModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_longitude
     *
     * @return the value of sensor.sensor_longitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorLongitude() {
        return sensorLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_longitude
     *
     * @param sensorLongitude the value for sensor.sensor_longitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorLongitude(String sensorLongitude) {
        this.sensorLongitude = sensorLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_latitude
     *
     * @return the value of sensor.sensor_latitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorLatitude() {
        return sensorLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_latitude
     *
     * @param sensorLatitude the value for sensor.sensor_latitude
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorLatitude(String sensorLatitude) {
        this.sensorLatitude = sensorLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_place
     *
     * @return the value of sensor.sensor_place
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorPlace() {
        return sensorPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_place
     *
     * @param sensorPlace the value for sensor.sensor_place
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorPlace(String sensorPlace) {
        this.sensorPlace = sensorPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.sensor_depth
     *
     * @return the value of sensor.sensor_depth
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Float getSensorDepth() {
        return sensorDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.sensor_depth
     *
     * @param sensorDepth the value for sensor.sensor_depth
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorDepth(Float sensorDepth) {
        this.sensorDepth = sensorDepth;
    }
}