package com.zd.manager.business.model;

public class StatisticChart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.statistic_chart_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer statisticChartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.detection_type_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer detectionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.detection_type_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String detectionTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.table_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.attributes
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String attributes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_chart.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String sensorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.statistic_chart_id
     *
     * @return the value of statistic_chart.statistic_chart_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getStatisticChartId() {
        return statisticChartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.statistic_chart_id
     *
     * @param statisticChartId the value for statistic_chart.statistic_chart_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setStatisticChartId(Integer statisticChartId) {
        this.statisticChartId = statisticChartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.project_id
     *
     * @return the value of statistic_chart.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.project_id
     *
     * @param projectId the value for statistic_chart.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.detection_type_id
     *
     * @return the value of statistic_chart.detection_type_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getDetectionTypeId() {
        return detectionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.detection_type_id
     *
     * @param detectionTypeId the value for statistic_chart.detection_type_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setDetectionTypeId(Integer detectionTypeId) {
        this.detectionTypeId = detectionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.detection_type_name
     *
     * @return the value of statistic_chart.detection_type_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getDetectionTypeName() {
        return detectionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.detection_type_name
     *
     * @param detectionTypeName the value for statistic_chart.detection_type_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setDetectionTypeName(String detectionTypeName) {
        this.detectionTypeName = detectionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.table_name
     *
     * @return the value of statistic_chart.table_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.table_name
     *
     * @param tableName the value for statistic_chart.table_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.attributes
     *
     * @return the value of statistic_chart.attributes
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.attributes
     *
     * @param attributes the value for statistic_chart.attributes
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_chart.sensor_id
     *
     * @return the value of statistic_chart.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_chart.sensor_id
     *
     * @param sensorId the value for statistic_chart.sensor_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSensorId(String sensorId) {
        this.sensorId = sensorId;
    }
}