package com.zd.manager.business.model;

public class SysCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.sc_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.type_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.type_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String typeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.type_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.item_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.item_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String itemValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.sc_id
     *
     * @return the value of sys_code.sc_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.sc_id
     *
     * @param scId the value for sys_code.sc_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.type_name
     *
     * @return the value of sys_code.type_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.type_name
     *
     * @param typeName the value for sys_code.type_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.type_value
     *
     * @return the value of sys_code.type_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getTypeValue() {
        return typeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.type_value
     *
     * @param typeValue the value for sys_code.type_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setTypeValue(String typeValue) {
        this.typeValue = typeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.type_code
     *
     * @return the value of sys_code.type_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.type_code
     *
     * @param typeCode the value for sys_code.type_code
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setTypeCode(Integer typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.item_name
     *
     * @return the value of sys_code.item_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.item_name
     *
     * @param itemName the value for sys_code.item_name
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.item_value
     *
     * @return the value of sys_code.item_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.item_value
     *
     * @param itemValue the value for sys_code.item_value
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }
}