package com.zd.manager.business.model;

import java.util.Date;

public class TerminalsLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.Id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.smu_rssi
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuRssi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.smu_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.smu_voltage
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_log.update_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.Id
     *
     * @return the value of terminals_log.Id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.Id
     *
     * @param id the value for terminals_log.Id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.type
     *
     * @return the value of terminals_log.type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.type
     *
     * @param type the value for terminals_log.type
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.smu_id
     *
     * @return the value of terminals_log.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuId() {
        return smuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.smu_id
     *
     * @param smuId the value for terminals_log.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuId(String smuId) {
        this.smuId = smuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.smu_rssi
     *
     * @return the value of terminals_log.smu_rssi
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuRssi() {
        return smuRssi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.smu_rssi
     *
     * @param smuRssi the value for terminals_log.smu_rssi
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuRssi(String smuRssi) {
        this.smuRssi = smuRssi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.smu_status
     *
     * @return the value of terminals_log.smu_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuStatus() {
        return smuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.smu_status
     *
     * @param smuStatus the value for terminals_log.smu_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuStatus(String smuStatus) {
        this.smuStatus = smuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.smu_voltage
     *
     * @return the value of terminals_log.smu_voltage
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuVoltage() {
        return smuVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.smu_voltage
     *
     * @param smuVoltage the value for terminals_log.smu_voltage
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuVoltage(String smuVoltage) {
        this.smuVoltage = smuVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_log.update_time
     *
     * @return the value of terminals_log.update_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_log.update_time
     *
     * @param updateTime the value for terminals_log.update_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}