package com.zd.manager.business.model;

public class TerminalsProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_project.tp_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer tpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_project.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals_project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_project.tp_id
     *
     * @return the value of terminals_project.tp_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_project.tp_id
     *
     * @param tpId the value for terminals_project.tp_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_project.smu_id
     *
     * @return the value of terminals_project.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuId() {
        return smuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_project.smu_id
     *
     * @param smuId the value for terminals_project.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuId(String smuId) {
        this.smuId = smuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals_project.project_id
     *
     * @return the value of terminals_project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals_project.project_id
     *
     * @param projectId the value for terminals_project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}