package com.zd.manager.business.model;

import java.util.Date;

public class Terminals {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.Id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.create_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.update_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_rssi
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer smuRssi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer smuStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_pow_st
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuPowSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_bat_st
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuBatSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_voltage
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.smu_versions
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private String smuVersions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminals.times_interval
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer timesInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.Id
     *
     * @return the value of terminals.Id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.Id
     *
     * @param id the value for terminals.Id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.create_time
     *
     * @return the value of terminals.create_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.create_time
     *
     * @param createTime the value for terminals.create_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.update_time
     *
     * @return the value of terminals.update_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.update_time
     *
     * @param updateTime the value for terminals.update_time
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_id
     *
     * @return the value of terminals.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuId() {
        return smuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_id
     *
     * @param smuId the value for terminals.smu_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuId(String smuId) {
        this.smuId = smuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_rssi
     *
     * @return the value of terminals.smu_rssi
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getSmuRssi() {
        return smuRssi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_rssi
     *
     * @param smuRssi the value for terminals.smu_rssi
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuRssi(Integer smuRssi) {
        this.smuRssi = smuRssi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_status
     *
     * @return the value of terminals.smu_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getSmuStatus() {
        return smuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_status
     *
     * @param smuStatus the value for terminals.smu_status
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuStatus(Integer smuStatus) {
        this.smuStatus = smuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_pow_st
     *
     * @return the value of terminals.smu_pow_st
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuPowSt() {
        return smuPowSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_pow_st
     *
     * @param smuPowSt the value for terminals.smu_pow_st
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuPowSt(String smuPowSt) {
        this.smuPowSt = smuPowSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_bat_st
     *
     * @return the value of terminals.smu_bat_st
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuBatSt() {
        return smuBatSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_bat_st
     *
     * @param smuBatSt the value for terminals.smu_bat_st
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuBatSt(String smuBatSt) {
        this.smuBatSt = smuBatSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_voltage
     *
     * @return the value of terminals.smu_voltage
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuVoltage() {
        return smuVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_voltage
     *
     * @param smuVoltage the value for terminals.smu_voltage
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuVoltage(String smuVoltage) {
        this.smuVoltage = smuVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.smu_versions
     *
     * @return the value of terminals.smu_versions
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public String getSmuVersions() {
        return smuVersions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.smu_versions
     *
     * @param smuVersions the value for terminals.smu_versions
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setSmuVersions(String smuVersions) {
        this.smuVersions = smuVersions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminals.times_interval
     *
     * @return the value of terminals.times_interval
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getTimesInterval() {
        return timesInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminals.times_interval
     *
     * @param timesInterval the value for terminals.times_interval
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setTimesInterval(Integer timesInterval) {
        this.timesInterval = timesInterval;
    }
}