package com.zd.manager.business.model;

import java.io.Serializable;

public class UserProject implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.up_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer upId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.user_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.leader_flag
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    private Boolean leaderFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.up_id
     *
     * @return the value of user_project.up_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getUpId() {
        return upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.up_id
     *
     * @param upId the value for user_project.up_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setUpId(Integer upId) {
        this.upId = upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.user_id
     *
     * @return the value of user_project.user_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.user_id
     *
     * @param userId the value for user_project.user_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.project_id
     *
     * @return the value of user_project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.project_id
     *
     * @param projectId the value for user_project.project_id
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.leader_flag
     *
     * @return the value of user_project.leader_flag
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public Boolean getLeaderFlag() {
        return leaderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.leader_flag
     *
     * @param leaderFlag the value for user_project.leader_flag
     *
     * @mbg.generated Tue Jul 10 10:42:30 CST 2018
     */
    public void setLeaderFlag(Boolean leaderFlag) {
        this.leaderFlag = leaderFlag;
    }
}